import Link from "next/link";
import { Button, buttonVariants } from "@/components/ui/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { computeResponseAverage, type CsatResponseRow } from "@/lib/csat-queries";
import { deleteCsatResponseAction } from "@/lib/csat-actions";

function formatDate(date: Date) {
  return new Intl.DateTimeFormat("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  }).format(date);
}

export function CsatResponseTable({
  responses,
  isAdmin,
  showGeneratedBy = true,
}: {
  responses: CsatResponseRow[];
  isAdmin: boolean;
  showGeneratedBy?: boolean;
}) {
  const columnCount = 5 + (showGeneratedBy ? 1 : 0) + (isAdmin ? 1 : 0);

  return (
    <Table>
      <TableHeader>
        <TableRow>
          <TableHead>Date</TableHead>
          <TableHead>Score</TableHead>
          <TableHead>From</TableHead>
          <TableHead>Answers</TableHead>
          <TableHead>Comment</TableHead>
          {showGeneratedBy && <TableHead>Generated by</TableHead>}
          {isAdmin && <TableHead className="text-right">Actions</TableHead>}
        </TableRow>
      </TableHeader>
      <TableBody>
        {responses.map((r) => {
          const avg = computeResponseAverage(r);
          return (
            <TableRow key={r.id}>
              <TableCell className="whitespace-nowrap">{formatDate(r.submittedAt)}</TableCell>
              <TableCell>{avg === null ? "—" : `${avg.toFixed(1)} / 5`}</TableCell>
              <TableCell>{r.respondentName ?? "—"}</TableCell>
              <TableCell className="max-w-xs text-sm">
                <details>
                  <summary className="cursor-pointer">{r.answers.length} question(s)</summary>
                  <ul className="mt-1 space-y-0.5">
                    {r.answers.map((a) => (
                      <li key={a.id}>
                        {a.csatLinkQuestion.text}: {a.score} / 5
                      </li>
                    ))}
                  </ul>
                </details>
              </TableCell>
              <TableCell className="max-w-xs truncate text-sm">{r.comment ?? "—"}</TableCell>
              {showGeneratedBy && <TableCell>{r.csatLink.createdBy.name}</TableCell>}
              {isAdmin && (
                <TableCell className="text-right">
                  <div className="flex justify-end gap-2">
                    <Link
                      href={`/csat-responses/${r.id}/edit`}
                      className={buttonVariants({ variant: "outline", size: "sm" })}
                    >
                      Edit
                    </Link>
                    <form action={deleteCsatResponseAction}>
                      <input type="hidden" name="id" value={r.id} />
                      <Button variant="outline" size="sm" type="submit">
                        Delete
                      </Button>
                    </form>
                  </div>
                </TableCell>
              )}
            </TableRow>
          );
        })}
        {responses.length === 0 && (
          <TableRow>
            <TableCell colSpan={columnCount} className="text-muted-foreground">
              No CSAT responses yet.
            </TableCell>
          </TableRow>
        )}
      </TableBody>
    </Table>
  );
}
