import { headers } from "next/headers";
import { notFound } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { CopyButton } from "@/components/copy-button";
import { CsatResponseTable } from "@/components/csat-response-table";
import { requireUser } from "@/lib/auth-guards";
import { getLinkCsatResponses } from "@/lib/csat-queries";
import { prisma } from "@/lib/prisma";

export default async function CsatLinkDetailPage({
  params,
}: {
  params: Promise<{ linkId: string }>;
}) {
  const { linkId } = await params;
  const user = await requireUser();

  const [link, hdrs] = await Promise.all([
    prisma.csatLink.findUnique({
      where: { id: linkId },
      include: {
        account: true,
        createdBy: true,
        questions: { orderBy: { sortOrder: "asc" } },
      },
    }),
    headers(),
  ]);
  if (!link) notFound();

  const responses = await getLinkCsatResponses(linkId);

  const host = hdrs.get("host");
  const protocol = host?.startsWith("localhost") ? "http" : "https";
  const url = `${protocol}://${host}/csat/${link.token}`;
  const isRevoked = !!link.revokedAt;
  const isAdmin = user.role === "ADMIN";

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-2">
        <h1 className="text-xl font-semibold">{link.account.name}</h1>
        <Badge variant={isRevoked ? "destructive" : "secondary"}>
          {isRevoked ? "Revoked" : "Active"}
        </Badge>
      </div>
      <p className="text-muted-foreground text-sm">
        Generated by {link.createdBy.name} on{" "}
        {new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short", year: "numeric" }).format(
          link.createdAt
        )}
      </p>

      <div className="flex items-center gap-2">
        <Input readOnly value={url} className="h-8 max-w-md text-xs" />
        <CopyButton text={url} />
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Questions</CardTitle>
        </CardHeader>
        <CardContent>
          <ol className="list-inside list-decimal space-y-1 text-sm">
            {link.questions.map((q) => (
              <li key={q.id}>{q.text}</li>
            ))}
          </ol>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Responses</CardTitle>
        </CardHeader>
        <CardContent>
          <CsatResponseTable responses={responses} isAdmin={isAdmin} showGeneratedBy={false} />
        </CardContent>
      </Card>
    </div>
  );
}
